language: php

cache:
  directories:
    - bin
    - $HOME/.composer/cache

sudo: false

matrix:
  include:
    - php: 5.4
      env:
        - DEPENDENCIES='low'
    - php: 5.5
    - php: 5.6
      env:
        - SYMFONY_VERSION=2.6.*
    - php: 5.6
      env:
        - SYMFONY_VERSION=2.7.*
    - php: 5.6
      env:
        - SYMFONY_VERSION=2.8.*
    - php: 7.0

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - if [[ "$DEPENDENCIES" != "low" && ! $SYMFONY_VERSION ]]; then composer update --prefer-source; fi;
  - if [[ "$DEPENDENCIES" != "low" && $SYMFONY_VERSION ]]; then composer require symfony/symfony:${SYMFONY_VERSION} -n --prefer-source; fi;
  - if [[ "$DEPENDENCIES" == "low" ]]; then composer update --prefer-lowest --prefer-source; fi;
  - "[ ! -f bin/selenium.jar ] && wget -O bin/selenium.jar http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar || true"
  - php features/fixtures/project/app/console assets:install --symlink features/fixtures/project/web

before_script:
  - nohup php -S localhost:8080 -t features/fixtures/project/web > /tmp/server.log 2>&1 &
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - java -jar bin/selenium.jar > /dev/null 2>&1 &
  - sleep 5

script:
  - bin/phpspec run -f pretty
  - bin/behat --no-snippets --format=progress --profile=travis -v

after_failure:
  - cat /tmp/FSiAdminSecurityBundle/logs/test.log
  - cat /tmp/server.log
