language: php

cache:
  directories:
    - bin
    - vendor
    - $HOME/.composer/cache

sudo: false

matrix:
  include:
    - php: 5.4
      env:
        - COMPOSER_FLAGS='--prefer-lowest'
    - php: 5.5
    - php: 5.6
      env:
        - SYMFONY_VERSION=2.7.*
    - php: 5.6
      env:
        - SYMFONY_VERSION=2.8.*
    - php: 5.6
    - php: 7.0
    - php: 7.1

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - if [[ $SYMFONY_VERSION ]]; then composer require symfony/symfony:${SYMFONY_VERSION} -n --no-update; fi;
  - "[ ! -f bin/selenium.jar ] && wget -O bin/selenium.jar http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar || true"
  - composer update $COMPOSER_FLAGS

before_script:
  - nohup php -S localhost:8080 -t features/fixtures/project/web > /tmp/server.log 2>&1 &
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - java -jar bin/selenium.jar > /dev/null 2>&1 &
  - sleep 5
  - php features/fixtures/project/app/console assets:install --symlink features/fixtures/project/web

script:
  - bin/phpspec run -f pretty
  - bin/behat --no-snippets --format=progress --profile=travis -v

after_failure:
  - cat /tmp/FSiAdminSecurityBundle/logs/test.log
  - cat /tmp/server.log
