language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*@dev
  - SYMFONY_VERSION=dev-master

sudo: false

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
    - php: hhvm
  exclude:
    - env: SYMFONY_VERSION=dev-master
      php: 5.4

install:
    - composer require symfony/symfony:${SYMFONY_VERSION} -n --prefer-source

script:
    - bin/phpspec run -f pretty
    - bin/behat --no-snippets --verbose --format=progress
